version: "3.5"

services:

  nextcloud:
    image: nextcloud:latest
    volumes:
      - ./nextcloud:/var/www/html:rw # moutn nextcloud files folder
      - ./Data:/data:rw # mount your personal data folder
    restart: always
  
  aria2:
    image: wahyd4/aria2-ui:nextcloud
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./Data:/data # mount your personal data folder
    # volumes:
      # - /app/a.db:/app/filebrowser.db
      # - /yoursslkeys/:/app/conf/key
      # - <the folder of aria2.conf and aria2.session>:/app/conf
    environment:
      - DOMAIN=:80 #domain, for https just bind domain like this https://example.com
      # - PUID=1000 # bind custom linux user id
      # - PGID=1000 # bind custom linux group id
      - ENABLE_AUTH=true # enable authentication for aria2
      # - RPC_SECRET=Hello # aria2 rpc secret
      # - ARIA2_SSL=false
      - ARIA2_USER=adm # aria2 login user
      - ARIA2_PWD=pwd  # aria2 login password
    links:
      - nextcloud:file-manager
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8081 # QB webui的端口，你可以换成其他端口
    volumes:
      - ./qbittorrent:/config
      - ./Data/Downloads:/downloads   # 替换成你自己的下载文件夹

  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./nzbget:/config
      - ./Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 8082:6789 
      
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./sabnzbd:/config
      - ./Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 8083:8080 #  注意此端口和qBittorrent冲突，请把左边的端口改成非冲突端口
      - 9090:9090    

  plex:
      image: spritsail/plex-media-server
      container_name: plex
      volumes:
        - ./Data/Movies:/media:rw # The media folder
        - ./transcode:/transcode # Transcoder temporary directory
        - ./plex:/config # Configurations
      environment:
        - LOG_DEBUG=0
        - LOG_VERBOSE=0
        - PLEX_CLAIM=claim-q-PxgeTtLVm7YE-aW2sL # Replace this TOKEN!!!
      restart: unless-stopped
      hostname: "PLXerver" # change the name to whatever you like
      ports:
        - "32400:32400" # The web port
        - "3005:3005" # The following ports are optional
        - "8324:8324"
        - "32469:32469"
        - "1900:1900"
        - "32410:32410"
        - "32412:32412"
        - "32413:32413"
        - "32414:32414"

  emby:
    image: emby/embyserver
    container_name: embyserver
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - GIDLIST=100
    volumes:
      - ./emby:/config
      - ./Data/Movies:/volume1/Data/Movies     # 替换成你自己的电影文件夹

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./prowlarr:/config
      - ./Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 9696:9696

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./jackett:/config
      - ./Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 9117:9117

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - 8191:8191

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./radarr:/config
      - /root/plx:/volume1 # 注意这里不再是下载文件夹，需要是下载/电影/剧集文件夹的母文件夹
    ports:
      - 7878:7878
      
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0 # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./sonarr:/config
      - /root/plx:/volume1 # 注意这里不再是下载文件夹，需要是下载/电影/剧集文件夹的母文件夹
    ports:
      - 8989:8989
      
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    ports:
      - 5055:5055
    volumes:
      - ./overseerr:/app/config
          
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./ombi:/config
    ports:
      - 3579:3579
      
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./chinesesubfinder:/config
      - ./Data/Movies:/volume1/Data/Movies

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./bazarr:/config
      - ./Data/Movies:/volume1/Data/Movies     # 替换成你自己的电影文件夹   # - /volume1:/volume1 你也可以选择这种整个映射的形式
    ports:
      - 6767:6767
