version: "3.5"

services:

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./prowlarr:/config
      - /root/plx/Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 9696:9696

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./jackett:/config
      - /root/plx/Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 9117:9117

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:
      - 8191:8191