version: "3.5"

services:


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080 # QB webui的端口，你可以换成其他端口
    volumes:
      - ./qbittorrent:/config
      - /root/plx/Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped  

  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./nzbget:/config
      - /root/plx/Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 8082:6789 
      
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./sabnzbd:/config
      - /root/plx/Data/Downloads:/downloads   # 替换成你自己的下载文件夹
    ports:
      - 8083:8080 #  注意此端口和qBittorrent冲突，请把左边的端口改成非冲突端口
      - 9090:9090    