version: "3.5"

services:
 
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    ports:
      - 5055:5055
    volumes:
      - ./overseerr:/app/config
          
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./ombi:/config
    ports:
      - 3579:3579
      
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./chinesesubfinder:/config
      - /root/plx/Data/Movies:/volume1/Data/Movies

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=0 # 注意替换
      - PGID=0  # 注意替换
      - TZ=Asia/Shanghai
    volumes:
      - ./bazarr:/config
      - /root/plx/Data/Movies:/volume1/Data/Movies     # 替换成你自己的电影文件夹   # - /volume1:/volume1 你也可以选择这种整个映射的形式
    ports:
      - 6767:6767